### ISSUE TITLE
CBS Paragraph Reader Role and Assignments

### ISSUE THREAD

**Issue by jezzar042015** [jezzar042015/kh-schedules#26]
### TASKS

- [x] Add role
- [x] Display assignment UI
- [x] Store/Read Assignment
- [x] Update source jsons

### BRANCH

```
git fetch origin
git checkout 26-cbs-reader
```
